### ISSUE TITLE
Infinite loop with some edge cases

### ISSUE THREAD

**Issue by timothyhale** [TeamprojektDomaincreator/domaincreator#19]
![image](https://github.com/TeamprojektDomaincreator/domaincreator/assets/83727307/a540a382-0bce-48bb-9fd5-043652965e5f)

**Comment by luis-stumpf** [comment]
could may be just be a problem with the length of the outlines array. have to test again when sams MR is merged

**Comment by timothyhale** [comment]
> could may be just be a problem with the length of the outlines array. have to test again when sams MR is merged
@luis-stumpf  Is this still occuring?
